// Code generated by Kitex v0.7.3. DO NOT EDIT.

package userservice

import (
	"context"
	user "github.com/DontSerious/Blog-Management-System-Backend/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateUser(ctx context.Context, req *user.CreateUserRequest, callOptions ...callopt.Option) (r *user.CreateUserResponse, err error)
	CheckUser(ctx context.Context, req *user.CheckUserRequest, callOptions ...callopt.Option) (r *user.CheckUserResponse, err error)
	ChangePWD(ctx context.Context, req *user.ChangePWDRequest, callOptions ...callopt.Option) (r *user.ChangePWDResponse, err error)
	DelUser(ctx context.Context, req *user.DelUserRequest, callOptions ...callopt.Option) (r *user.DelUserResponse, err error)
	GetAllUser(ctx context.Context, callOptions ...callopt.Option) (r *user.GetAllUserResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) CreateUser(ctx context.Context, req *user.CreateUserRequest, callOptions ...callopt.Option) (r *user.CreateUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUser(ctx, req)
}

func (p *kUserServiceClient) CheckUser(ctx context.Context, req *user.CheckUserRequest, callOptions ...callopt.Option) (r *user.CheckUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckUser(ctx, req)
}

func (p *kUserServiceClient) ChangePWD(ctx context.Context, req *user.ChangePWDRequest, callOptions ...callopt.Option) (r *user.ChangePWDResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePWD(ctx, req)
}

func (p *kUserServiceClient) DelUser(ctx context.Context, req *user.DelUserRequest, callOptions ...callopt.Option) (r *user.DelUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DelUser(ctx, req)
}

func (p *kUserServiceClient) GetAllUser(ctx context.Context, callOptions ...callopt.Option) (r *user.GetAllUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAllUser(ctx)
}
